version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: blockverify
      POSTGRES_PASSWORD: localpass123
      POSTGRES_DB: blockverify
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blockverify"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://blockverify:localpass123@postgres:5432/blockverify
      ISSUER_KEY_FILE: issuer_ed25519.jwk
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./client_sdk:/app/client_sdk
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: 