# Railway configuration for full B2B system
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.full"

[deploy]
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 